language: python
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.4'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.5
before_install:
- wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh
  -O install.sh
- chmod +x install.sh
- travis_retry bash -x ./install.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- travis_retry conda install pycparser -y --name travisci
before_script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py test
script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import lim; lim.test()"
- popd
deploy:
  provider: pypi
  skip_cleanup: true
  user: danilo.horta
  password:
    secure: Oa1VrmGDEXlX4JYDGfppv9LL+DQgVD4g9rxo8tSvCDqsx+XyUSeyE/el4FrKthssQBpkYVlrIk7tDkwy8hbUiUtg9HcFnVyD52ys0gKhh4RSpLCV5XuDkCzytNHbUs2QuFqjd6TaV3HFNglwd12JTiyJvkqdvLsLoOXg+V4oPuVvIyBpiUc6I9/d5MX6UnvQZ1/Tp6V8icbb1ssMZfDY9ZrERlJqI6rNzg0DIR6RD8UVnlGuwthCI3J5lw3LudweoED/1pA9W850iDyrjbNdIvCjuJXZ276DWTmWehhxw7gEN8dgFUnI0KAr6NZL2rL3jugW9m6g/uGvDz2ktnHuqrQzf0jRIpllu2nucYgLXvmdeP/4QSH38gLPYLI8dA1rqtF/35x+YSD+jKcx1OBIKh38PTDeGjEMR3Fua6s6+83hgyV0cUnNGYY8n5AKzCW9bHhR1EKy3jUiqL7unLAOQ/vp0Pqyi/EOPCHgM0TFtdJTh7ED99nzHaaD9IuSKy+SkmEJ5em4gKhbYojVD/iSNG2GeC3ynBzw+HVniZlPY1lhOAT5JriDLkpcuaRBoAs5S5xZJasXkpfO4yRdKS9QiMrJ8vdtpUM/dZ9VXNhCKv2kGECn0B7dhRnJDDEBe6kDp69GkdzfzBguIRaAUR3j06BZdrqf7F3g0lfMgbdXGa8=
  on:
    branch: master
notifications:
  email: false
