name: py35
channels:
- r
- defaults
- conda-forge
dependencies:
- cffi=1.9.1=py35_0
- conda-forge::asciitree=0.3.3=py35_0
- conda-forge::brent_search=1.0.15=py35_0
- conda-forge::cachetools=2.0.0=py35_0
- conda-forge::humanfriendly=1.44.7=py35_2
- conda-forge::limix_util=1.0.7=py35_0
- conda-forge::ncephes=1.0.14=py35_0
- conda-forge::ndarray_listener=1.0.15=py35_0
- conda-forge::numpy_sugar=1.0.8=py35_0
- conda-forge::optimix=1.1.1=py35_0
- conda-forge::progressbar2=3.10.1=py35_0
- conda-forge::pytest-runner=2.9=py35_1
- conda-forge::python-utils=2.0.0=py35_0
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- llvmlite=0.14.0=py35_0
- mkl=11.3.3=0
- nose=1.3.7=py35_1
- numba=0.29.0=np111py35_0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.1=np111py35_0
- pip=9.0.1=py35_1
- py=1.4.31=py35_0
- pycparser=2.17=py35_0
- pytest=3.0.5=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- readline=6.2=2
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tabulate=0.7.5=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - brent-search==1.0.15
  - limix-util==1.0.7
  - ndarray-listener==1.0.15
  - numpy-sugar==1.0.8
